dtype: bfloat16
merge_method: linear
modules:
  default:
    slices:
    - sources:
      - layer_range: [0, 6]
        model: EleutherAI/pythia-70m-deduped
        parameters:
          weight: 0.3333333432674408
      - layer_range: [0, 6]
        model: EleutherAI/pythia-70m-deduped
        parameters:
          weight: 0.3333333432674408
      - layer_range: [0, 6]
        model: EleutherAI/pythia-70m-deduped
        parameters:
          weight: 0.3333333432674408
parameters:
  int8_mask: 1.0
  normalize: 1.0