apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: __RAY_JOB_NAME__
  annotations:
    mergekit/run-purpose: "ga-experiment"
spec:
  entrypoint: >-
    __MERGEKIT_ENTRYPOINT__
  runtimeEnvYAML: |
    env_vars:
      HF_HOME: "/data/hf"
      MERGEKIT_DATA_DIR: "/data/artifacts"
      AWS_REGION: "__AWS_REGION__"
      TOKENIZERS_PARALLELISM: "false"
  clusterSelector:
    ray.io/cluster: __RAY_CLUSTER_NAME__
  shutdownAfterJobFinishes: false
