apiVersion: v1
kind: PersistentVolume
metadata:
  name: mergekit-shared-pv
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-static
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "__EFS_FILE_SYSTEM_ID__"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mergekit-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: efs-static
  volumeName: mergekit-shared-pv
